### ISSUE TITLE
Make a new tag

### ISSUE THREAD

**Issue by asecondwill** [heyday/silverstripe-responsive-images#8]
The master branch broke for me for some reason, rolling back to 0.1.1 fixed it.  

I noticed the latest tag release is 2 years old, so it seems better to run on master, but that has these risks.  What version do you recommend and is it possible to get a new release tagged?

**Comment by stecman** [comment]
Hi @asecondwill, all but the most recent commit since the last release (0.1.1, one year ago) are non-functional, so there hasn't been a need to tag a new release. Anything can happen outside of tagged releases and version development branches, so it's really best to avoid using `dev-master` unless you're actually contributing to a package.

The master branch has recently had [a change](https://github.com/heyday/silverstripe-responsive-images/pull/6#issuecomment-120767028) merged into it that is known to break backwards compatibility as it requires a change to the configuration to continue working. Since this module is pre-1.0, this changes can be released as a new minor version; we just haven't tagged it yet. If you'd like to use what's currently sitting on master, we can put some upgrade notes together and tag that as `0.2.0`.
